# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 634)
        MainWindow.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 991, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.lbl_supplier = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lbl_supplier.setGeometry(QtCore.QRect(10, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_supplier.setFont(font)
        self.lbl_supplier.setObjectName("lbl_supplier")
        self.time_schedule = QtWidgets.QTimeEdit(self.tabWidgetPage1)
        self.time_schedule.setGeometry(QtCore.QRect(350, 50, 161, 31))
        self.time_schedule.setObjectName("time_schedule")
        self.lne_user = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lne_user.setGeometry(QtCore.QRect(110, 170, 161, 25))
        self.lne_user.setObjectName("lne_user")
        self.spn_max = QtWidgets.QSpinBox(self.tabWidgetPage1)
        self.spn_max.setGeometry(QtCore.QRect(460, 110, 51, 26))
        self.spn_max.setMinimum(20)
        self.spn_max.setObjectName("spn_max")
        self.lbl_file = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lbl_file.setGeometry(QtCore.QRect(10, 230, 71, 21))
        self.lbl_file.setObjectName("lbl_file")
        self.lbl_user = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lbl_user.setGeometry(QtCore.QRect(10, 170, 41, 21))
        self.lbl_user.setObjectName("lbl_user")
        self.lbl_min = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lbl_min.setGeometry(QtCore.QRect(10, 140, 31, 21))
        self.lbl_min.setObjectName("lbl_min")
        self.lbl_type = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lbl_type.setGeometry(QtCore.QRect(10, 50, 67, 21))
        self.lbl_type.setObjectName("lbl_type")
        self.lbl_max = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lbl_max.setGeometry(QtCore.QRect(10, 110, 31, 21))
        self.lbl_max.setObjectName("lbl_max")
        self.btn_test = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.btn_test.setGeometry(QtCore.QRect(430, 260, 80, 25))
        self.btn_test.setObjectName("btn_test")
        self.lbl_passwd = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lbl_passwd.setGeometry(QtCore.QRect(10, 200, 71, 21))
        self.lbl_passwd.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lbl_passwd.setObjectName("lbl_passwd")
        self.lcdNumber = QtWidgets.QLCDNumber(self.tabWidgetPage1)
        self.lcdNumber.setGeometry(QtCore.QRect(350, 250, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.spn_min = QtWidgets.QSpinBox(self.tabWidgetPage1)
        self.spn_min.setGeometry(QtCore.QRect(460, 140, 51, 26))
        self.spn_min.setObjectName("spn_min")
        self.lne_passwd = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lne_passwd.setGeometry(QtCore.QRect(110, 200, 161, 25))
        self.lne_passwd.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lne_passwd.setObjectName("lne_passwd")
        self.chk_supplier_enabled = QtWidgets.QCheckBox(self.tabWidgetPage1)
        self.chk_supplier_enabled.setGeometry(QtCore.QRect(250, 80, 16, 23))
        self.chk_supplier_enabled.setText("")
        self.chk_supplier_enabled.setObjectName("chk_supplier_enabled")
        self.lbl_time = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lbl_time.setGeometry(QtCore.QRect(290, 50, 51, 21))
        self.lbl_time.setObjectName("lbl_time")
        self.lne_file = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.lne_file.setGeometry(QtCore.QRect(110, 230, 161, 25))
        self.lne_file.setObjectName("lne_file")
        self.lbl_type_2 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lbl_type_2.setGeometry(QtCore.QRect(10, 80, 67, 21))
        self.lbl_type_2.setObjectName("lbl_type_2")
        self.time_schedule_2 = QtWidgets.QTimeEdit(self.tabWidgetPage1)
        self.time_schedule_2.setGeometry(QtCore.QRect(350, 80, 161, 31))
        self.time_schedule_2.setObjectName("time_schedule_2")
        self.lbl_supplier_2 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lbl_supplier_2.setGeometry(QtCore.QRect(120, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_supplier_2.setFont(font)
        self.lbl_supplier_2.setObjectName("lbl_supplier_2")
        self.lbl_http = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lbl_http.setGeometry(QtCore.QRect(10, 270, 81, 17))
        self.lbl_http.setObjectName("lbl_http")
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.time_schedule_3 = QtWidgets.QTimeEdit(self.tabWidgetPage2)
        self.time_schedule_3.setGeometry(QtCore.QRect(370, 210, 161, 31))
        self.time_schedule_3.setObjectName("time_schedule_3")
        self.lne_user_3 = QtWidgets.QLineEdit(self.tabWidgetPage2)
        self.lne_user_3.setGeometry(QtCore.QRect(370, 120, 161, 25))
        self.lne_user_3.setObjectName("lne_user_3")
        self.spn_max_3 = QtWidgets.QSpinBox(self.tabWidgetPage2)
        self.spn_max_3.setGeometry(QtCore.QRect(370, 80, 51, 26))
        self.spn_max_3.setMinimum(20)
        self.spn_max_3.setObjectName("spn_max_3")
        self.lbl_file_3 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.lbl_file_3.setGeometry(QtCore.QRect(290, 180, 71, 21))
        self.lbl_file_3.setObjectName("lbl_file_3")
        self.lbl_user_3 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.lbl_user_3.setGeometry(QtCore.QRect(320, 120, 41, 21))
        self.lbl_user_3.setObjectName("lbl_user_3")
        self.lbl_min_3 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.lbl_min_3.setGeometry(QtCore.QRect(440, 80, 31, 21))
        self.lbl_min_3.setObjectName("lbl_min_3")
        self.lbl_type_3 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.lbl_type_3.setGeometry(QtCore.QRect(460, 10, 67, 21))
        self.lbl_type_3.setObjectName("lbl_type_3")
        self.treeView_3 = QtWidgets.QTreeView(self.tabWidgetPage2)
        self.treeView_3.setGeometry(QtCore.QRect(10, 50, 256, 192))
        self.treeView_3.setAnimated(True)
        self.treeView_3.setObjectName("treeView_3")
        self.lbl_max_3 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.lbl_max_3.setGeometry(QtCore.QRect(330, 80, 31, 21))
        self.lbl_max_3.setObjectName("lbl_max_3")
        self.btn_test_3 = QtWidgets.QPushButton(self.tabWidgetPage2)
        self.btn_test_3.setGeometry(QtCore.QRect(463, 320, 80, 25))
        self.btn_test_3.setObjectName("btn_test_3")
        self.lbl_passwd_3 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.lbl_passwd_3.setGeometry(QtCore.QRect(290, 150, 71, 21))
        self.lbl_passwd_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lbl_passwd_3.setObjectName("lbl_passwd_3")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.tabWidgetPage2)
        self.lcdNumber_3.setGeometry(QtCore.QRect(390, 320, 64, 23))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.spn_min_3 = QtWidgets.QSpinBox(self.tabWidgetPage2)
        self.spn_min_3.setGeometry(QtCore.QRect(480, 80, 51, 26))
        self.spn_min_3.setObjectName("spn_min_3")
        self.lne_passwd_3 = QtWidgets.QLineEdit(self.tabWidgetPage2)
        self.lne_passwd_3.setGeometry(QtCore.QRect(370, 150, 161, 25))
        self.lne_passwd_3.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lne_passwd_3.setObjectName("lne_passwd_3")
        self.lbl_supplier_3 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.lbl_supplier_3.setGeometry(QtCore.QRect(270, 10, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_supplier_3.setFont(font)
        self.lbl_supplier_3.setObjectName("lbl_supplier_3")
        self.chk_supplier_enabled_3 = QtWidgets.QCheckBox(self.tabWidgetPage2)
        self.chk_supplier_enabled_3.setGeometry(QtCore.QRect(390, 50, 141, 23))
        self.chk_supplier_enabled_3.setObjectName("chk_supplier_enabled_3")
        self.lbl_time_3 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.lbl_time_3.setGeometry(QtCore.QRect(310, 210, 51, 21))
        self.lbl_time_3.setObjectName("lbl_time_3")
        self.time_repeat_3 = QtWidgets.QTimeEdit(self.tabWidgetPage2)
        self.time_repeat_3.setGeometry(QtCore.QRect(370, 240, 161, 26))
        self.time_repeat_3.setObjectName("time_repeat_3")
        self.lne_file_3 = QtWidgets.QLineEdit(self.tabWidgetPage2)
        self.lne_file_3.setGeometry(QtCore.QRect(370, 180, 161, 25))
        self.lne_file_3.setObjectName("lne_file_3")
        self.toolBox = QtWidgets.QToolBox(self.tabWidgetPage2)
        self.toolBox.setGeometry(QtCore.QRect(-110, 240, 331, 231))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 331, 169))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        self.btn_test.clicked.connect(self.lbl_type.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_supplier.setText(_translate("MainWindow", "Supplier:"))
        self.lbl_file.setText(_translate("MainWindow", "FTP Path"))
        self.lbl_user.setText(_translate("MainWindow", "User"))
        self.lbl_min.setText(_translate("MainWindow", "Min"))
        self.lbl_type.setText(_translate("MainWindow", "Type: "))
        self.lbl_max.setText(_translate("MainWindow", "Max"))
        self.btn_test.setText(_translate("MainWindow", "Test"))
        self.lbl_passwd.setText(_translate("MainWindow", "Password"))
        self.lbl_time.setText(_translate("MainWindow", "Time"))
        self.lbl_type_2.setText(_translate("MainWindow", "Enabled"))
        self.lbl_supplier_2.setText(_translate("MainWindow", "xxxxxxx"))
        self.lbl_http.setText(_translate("MainWindow", "HTTP Link:"))
        self.lbl_file_3.setText(_translate("MainWindow", "FTP Path"))
        self.lbl_user_3.setText(_translate("MainWindow", "User"))
        self.lbl_min_3.setText(_translate("MainWindow", "Min"))
        self.lbl_type_3.setText(_translate("MainWindow", "Type: "))
        self.lbl_max_3.setText(_translate("MainWindow", "Max"))
        self.btn_test_3.setText(_translate("MainWindow", "Test"))
        self.lbl_passwd_3.setText(_translate("MainWindow", "Password"))
        self.lbl_supplier_3.setText(_translate("MainWindow", "Supplier Name 2"))
        self.chk_supplier_enabled_3.setText(_translate("MainWindow", "Enabled"))
        self.lbl_time_3.setText(_translate("MainWindow", "Time"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2"))


