# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'title_screen.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 790)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ASH-Black.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: rgb(49, 49, 49);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setGeometry(QtCore.QRect(10, 170, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_run.setFont(font)
        self.btn_run.setObjectName("btn_run")
        self.lbl_sms = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sms.setGeometry(QtCore.QRect(30, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.lbl_sms.setFont(font)
        self.lbl_sms.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_sms.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sms.setObjectName("lbl_sms")
        self.btn_config = QtWidgets.QPushButton(self.centralwidget)
        self.btn_config.setGeometry(QtCore.QRect(10, 240, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_config.setFont(font)
        self.btn_config.setObjectName("btn_config")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zero.setGeometry(QtCore.QRect(10, 310, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_zero.setFont(font)
        self.btn_zero.setObjectName("btn_zero")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 710, 181, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ashlogo.png"))
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(190, 0, 951, 791))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tabstax = QtWidgets.QWidget()
        self.tabstax.setAccessibleName("")
        self.tabstax.setObjectName("tabstax")
        self.lbl_supplier = QtWidgets.QLabel(self.tabstax)
        self.lbl_supplier.setGeometry(QtCore.QRect(10, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_supplier.setFont(font)
        self.lbl_supplier.setObjectName("lbl_supplier")
        self.time_schedule = QtWidgets.QTimeEdit(self.tabstax)
        self.time_schedule.setGeometry(QtCore.QRect(350, 50, 161, 31))
        self.time_schedule.setObjectName("time_schedule")
        self.lne_user = QtWidgets.QLineEdit(self.tabstax)
        self.lne_user.setGeometry(QtCore.QRect(110, 170, 161, 25))
        self.lne_user.setObjectName("lne_user")
        self.spn_max = QtWidgets.QSpinBox(self.tabstax)
        self.spn_max.setGeometry(QtCore.QRect(220, 110, 51, 26))
        self.spn_max.setMinimum(20)
        self.spn_max.setObjectName("spn_max")
        self.lbl_min = QtWidgets.QLabel(self.tabstax)
        self.lbl_min.setGeometry(QtCore.QRect(10, 140, 31, 21))
        self.lbl_min.setObjectName("lbl_min")
        self.lbl_t = QtWidgets.QLabel(self.tabstax)
        self.lbl_t.setGeometry(QtCore.QRect(10, 50, 67, 21))
        self.lbl_t.setObjectName("lbl_t")
        self.lbl_max = QtWidgets.QLabel(self.tabstax)
        self.lbl_max.setGeometry(QtCore.QRect(10, 110, 31, 21))
        self.lbl_max.setObjectName("lbl_max")
        self.btn_test = QtWidgets.QPushButton(self.tabstax)
        self.btn_test.setGeometry(QtCore.QRect(430, 260, 80, 25))
        self.btn_test.setObjectName("btn_test")
        self.spn_min = QtWidgets.QSpinBox(self.tabstax)
        self.spn_min.setGeometry(QtCore.QRect(220, 140, 51, 26))
        self.spn_min.setObjectName("spn_min")
        self.chk_supplier_enabled = QtWidgets.QCheckBox(self.tabstax)
        self.chk_supplier_enabled.setGeometry(QtCore.QRect(250, 80, 16, 23))
        self.chk_supplier_enabled.setText("")
        self.chk_supplier_enabled.setObjectName("chk_supplier_enabled")
        self.lbl_time = QtWidgets.QLabel(self.tabstax)
        self.lbl_time.setGeometry(QtCore.QRect(290, 50, 51, 21))
        self.lbl_time.setObjectName("lbl_time")
        self.lbl_enabled = QtWidgets.QLabel(self.tabstax)
        self.lbl_enabled.setGeometry(QtCore.QRect(10, 80, 67, 21))
        self.lbl_enabled.setObjectName("lbl_enabled")
        self.time_schedule_2 = QtWidgets.QTimeEdit(self.tabstax)
        self.time_schedule_2.setGeometry(QtCore.QRect(350, 80, 161, 31))
        self.time_schedule_2.setObjectName("time_schedule_2")
        self.lbl_s = QtWidgets.QLabel(self.tabstax)
        self.lbl_s.setGeometry(QtCore.QRect(120, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_s.setFont(font)
        self.lbl_s.setObjectName("lbl_s")
        self.lbl_http = QtWidgets.QLabel(self.tabstax)
        self.lbl_http.setGeometry(QtCore.QRect(10, 174, 81, 17))
        self.lbl_http.setObjectName("lbl_http")
        self.lbl_type = QtWidgets.QLabel(self.tabstax)
        self.lbl_type.setGeometry(QtCore.QRect(210, 50, 61, 21))
        self.lbl_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_type.setObjectName("lbl_type")
        self.tabWidget.addTab(self.tabstax, "")
        self.tabfps = QtWidgets.QWidget()
        self.tabfps.setObjectName("tabfps")
        self.lbl_s2 = QtWidgets.QLabel(self.tabfps)
        self.lbl_s2.setGeometry(QtCore.QRect(10, 2, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_s2.setFont(font)
        self.lbl_s2.setObjectName("lbl_s2")
        self.lbl_min_2 = QtWidgets.QLabel(self.tabfps)
        self.lbl_min_2.setGeometry(QtCore.QRect(10, 132, 31, 21))
        self.lbl_min_2.setObjectName("lbl_min_2")
        self.lbl_time_2 = QtWidgets.QLabel(self.tabfps)
        self.lbl_time_2.setGeometry(QtCore.QRect(290, 40, 51, 21))
        self.lbl_time_2.setObjectName("lbl_time_2")
        self.lbl_t2 = QtWidgets.QLabel(self.tabfps)
        self.lbl_t2.setGeometry(QtCore.QRect(10, 42, 67, 21))
        self.lbl_t2.setObjectName("lbl_t2")
        self.lbl_type2 = QtWidgets.QLabel(self.tabfps)
        self.lbl_type2.setGeometry(QtCore.QRect(210, 42, 61, 21))
        self.lbl_type2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_type2.setObjectName("lbl_type2")
        self.lbl_max_2 = QtWidgets.QLabel(self.tabfps)
        self.lbl_max_2.setGeometry(QtCore.QRect(10, 102, 31, 21))
        self.lbl_max_2.setObjectName("lbl_max_2")
        self.lbl_supplier2 = QtWidgets.QLabel(self.tabfps)
        self.lbl_supplier2.setGeometry(QtCore.QRect(120, 2, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_supplier2.setFont(font)
        self.lbl_supplier2.setObjectName("lbl_supplier2")
        self.spn_max_2 = QtWidgets.QSpinBox(self.tabfps)
        self.spn_max_2.setGeometry(QtCore.QRect(220, 102, 51, 26))
        self.spn_max_2.setMinimum(20)
        self.spn_max_2.setObjectName("spn_max_2")
        self.time_schedule_3 = QtWidgets.QTimeEdit(self.tabfps)
        self.time_schedule_3.setGeometry(QtCore.QRect(360, 70, 161, 31))
        self.time_schedule_3.setObjectName("time_schedule_3")
        self.lbl_enabled2 = QtWidgets.QLabel(self.tabfps)
        self.lbl_enabled2.setGeometry(QtCore.QRect(10, 72, 67, 21))
        self.lbl_enabled2.setObjectName("lbl_enabled2")
        self.chk_supplier_enabled_2 = QtWidgets.QCheckBox(self.tabfps)
        self.chk_supplier_enabled_2.setGeometry(QtCore.QRect(250, 70, 16, 23))
        self.chk_supplier_enabled_2.setText("")
        self.chk_supplier_enabled_2.setObjectName("chk_supplier_enabled_2")
        self.time_schedule_4 = QtWidgets.QTimeEdit(self.tabfps)
        self.time_schedule_4.setGeometry(QtCore.QRect(360, 30, 161, 31))
        self.time_schedule_4.setObjectName("time_schedule_4")
        self.spn_min_2 = QtWidgets.QSpinBox(self.tabfps)
        self.spn_min_2.setGeometry(QtCore.QRect(220, 132, 51, 26))
        self.spn_min_2.setObjectName("spn_min_2")
        self.btn_test_2 = QtWidgets.QPushButton(self.tabfps)
        self.btn_test_2.setGeometry(QtCore.QRect(430, 230, 80, 25))
        self.btn_test_2.setObjectName("btn_test_2")
        self.tabWidget.addTab(self.tabfps, "")
        self.tabbiztools = QtWidgets.QWidget()
        self.tabbiztools.setObjectName("tabbiztools")
        self.lbl_passwd_3 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_passwd_3.setGeometry(QtCore.QRect(0, 190, 71, 21))
        self.lbl_passwd_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lbl_passwd_3.setObjectName("lbl_passwd_3")
        self.lbl_s3 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_s3.setGeometry(QtCore.QRect(0, 0, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_s3.setFont(font)
        self.lbl_s3.setObjectName("lbl_s3")
        self.lbl_min_3 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_min_3.setGeometry(QtCore.QRect(0, 130, 31, 21))
        self.lbl_min_3.setObjectName("lbl_min_3")
        self.lbl_user_3 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_user_3.setGeometry(QtCore.QRect(0, 160, 41, 21))
        self.lbl_user_3.setObjectName("lbl_user_3")
        self.lbl_mon = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_mon.setGeometry(QtCore.QRect(330, 71, 61, 21))
        self.lbl_mon.setObjectName("lbl_mon")
        self.lbl_t3 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_t3.setGeometry(QtCore.QRect(0, 40, 67, 21))
        self.lbl_t3.setObjectName("lbl_t3")
        self.btn_save = QtWidgets.QPushButton(self.tabbiztools)
        self.btn_save.setGeometry(QtCore.QRect(90, 280, 101, 41))
        self.btn_save.setObjectName("btn_save")
        self.lbl_type3 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_type3.setGeometry(QtCore.QRect(200, 40, 61, 21))
        self.lbl_type3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_type3.setObjectName("lbl_type3")
        self.lbl_max_3 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_max_3.setGeometry(QtCore.QRect(0, 100, 31, 21))
        self.lbl_max_3.setObjectName("lbl_max_3")
        self.lbl_supplier_3 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_supplier_3.setGeometry(QtCore.QRect(110, 0, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_supplier_3.setFont(font)
        self.lbl_supplier_3.setObjectName("lbl_supplier_3")
        self.spn_max_3 = QtWidgets.QSpinBox(self.tabbiztools)
        self.spn_max_3.setGeometry(QtCore.QRect(210, 100, 51, 26))
        self.spn_max_3.setMinimum(20)
        self.spn_max_3.setObjectName("spn_max_3")
        self.lbl_enabled3 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_enabled3.setGeometry(QtCore.QRect(0, 70, 67, 21))
        self.lbl_enabled3.setObjectName("lbl_enabled3")
        self.lbl_file_3 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_file_3.setGeometry(QtCore.QRect(0, 220, 71, 21))
        self.lbl_file_3.setObjectName("lbl_file_3")
        self.chk_supplier_enabled_3 = QtWidgets.QCheckBox(self.tabbiztools)
        self.chk_supplier_enabled_3.setGeometry(QtCore.QRect(250, 70, 16, 23))
        self.chk_supplier_enabled_3.setText("")
        self.chk_supplier_enabled_3.setObjectName("chk_supplier_enabled_3")
        self.spn_min_3 = QtWidgets.QSpinBox(self.tabbiztools)
        self.spn_min_3.setGeometry(QtCore.QRect(210, 130, 51, 26))
        self.spn_min_3.setObjectName("spn_min_3")
        self.lbl_fri = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_fri.setGeometry(QtCore.QRect(300, 190, 71, 21))
        self.lbl_fri.setObjectName("lbl_fri")
        self.lbl_thu = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_thu.setGeometry(QtCore.QRect(300, 160, 71, 16))
        self.lbl_thu.setObjectName("lbl_thu")
        self.lbl_wed = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_wed.setGeometry(QtCore.QRect(300, 130, 81, 16))
        self.lbl_wed.setObjectName("lbl_wed")
        self.lbl_tue = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_tue.setGeometry(QtCore.QRect(330, 100, 61, 21))
        self.lbl_tue.setObjectName("lbl_tue")
        self.lbl_sun = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_sun.setGeometry(QtCore.QRect(300, 250, 71, 21))
        self.lbl_sun.setObjectName("lbl_sun")
        self.lbl_sat = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_sat.setGeometry(QtCore.QRect(300, 220, 71, 16))
        self.lbl_sat.setObjectName("lbl_sat")
        self.chk_mon = QtWidgets.QCheckBox(self.tabbiztools)
        self.chk_mon.setGeometry(QtCore.QRect(440, 70, 16, 23))
        self.chk_mon.setText("")
        self.chk_mon.setChecked(True)
        self.chk_mon.setObjectName("chk_mon")
        self.chk_thu = QtWidgets.QCheckBox(self.tabbiztools)
        self.chk_thu.setGeometry(QtCore.QRect(410, 160, 16, 23))
        self.chk_thu.setText("")
        self.chk_thu.setChecked(True)
        self.chk_thu.setObjectName("chk_thu")
        self.chk_wed = QtWidgets.QCheckBox(self.tabbiztools)
        self.chk_wed.setGeometry(QtCore.QRect(410, 130, 16, 23))
        self.chk_wed.setText("")
        self.chk_wed.setObjectName("chk_wed")
        self.chk_fri = QtWidgets.QCheckBox(self.tabbiztools)
        self.chk_fri.setGeometry(QtCore.QRect(410, 190, 16, 23))
        self.chk_fri.setText("")
        self.chk_fri.setObjectName("chk_fri")
        self.chk_tue = QtWidgets.QCheckBox(self.tabbiztools)
        self.chk_tue.setGeometry(QtCore.QRect(440, 100, 16, 23))
        self.chk_tue.setText("")
        self.chk_tue.setChecked(True)
        self.chk_tue.setObjectName("chk_tue")
        self.chk_sat = QtWidgets.QCheckBox(self.tabbiztools)
        self.chk_sat.setGeometry(QtCore.QRect(410, 220, 16, 23))
        self.chk_sat.setText("")
        self.chk_sat.setChecked(True)
        self.chk_sat.setObjectName("chk_sat")
        self.chk_sun = QtWidgets.QCheckBox(self.tabbiztools)
        self.chk_sun.setGeometry(QtCore.QRect(410, 250, 16, 21))
        self.chk_sun.setText("")
        self.chk_sun.setObjectName("chk_sun")
        self.time_schedule1 = QtWidgets.QTimeEdit(self.tabbiztools)
        self.time_schedule1.setGeometry(QtCore.QRect(520, 70, 161, 31))
        self.time_schedule1.setObjectName("time_schedule1")
        self.time_schedule2 = QtWidgets.QTimeEdit(self.tabbiztools)
        self.time_schedule2.setGeometry(QtCore.QRect(520, 100, 161, 31))
        self.time_schedule2.setObjectName("time_schedule2")
        self.lbl_type3_2 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_type3_2.setGeometry(QtCore.QRect(520, 40, 151, 21))
        self.lbl_type3_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_type3_2.setObjectName("lbl_type3_2")
        self.btn_add_time = QtWidgets.QPushButton(self.tabbiztools)
        self.btn_add_time.setGeometry(QtCore.QRect(710, 130, 80, 25))
        self.btn_add_time.setObjectName("btn_add_time")
        self.btn_remove_time2 = QtWidgets.QPushButton(self.tabbiztools)
        self.btn_remove_time2.setGeometry(QtCore.QRect(710, 100, 80, 25))
        self.btn_remove_time2.setObjectName("btn_remove_time2")
        self.btn_remove_time1 = QtWidgets.QPushButton(self.tabbiztools)
        self.btn_remove_time1.setGeometry(QtCore.QRect(710, 70, 80, 25))
        self.btn_remove_time1.setObjectName("btn_remove_time1")
        self.lbl_type3_3 = QtWidgets.QLabel(self.tabbiztools)
        self.lbl_type3_3.setGeometry(QtCore.QRect(280, 40, 151, 21))
        self.lbl_type3_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_type3_3.setObjectName("lbl_type3_3")
        self.tabWidget.addTab(self.tabbiztools, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 51, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(130, 150, 51, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(30, 210, 151, 17))
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(170, 205, 48, 26))
        self.spinBox.setObjectName("spinBox")
        self.listView = QtWidgets.QListView(self.tab)
        self.listView.setGeometry(QtCore.QRect(290, 60, 256, 192))
        self.listView.setObjectName("listView")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actiondygjdt = QtWidgets.QAction(MainWindow)
        self.actiondygjdt.setObjectName("actiondygjdt")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.btn_zero.clicked.connect(MainWindow.close)
        self.btn_config.clicked.connect(self.tabWidget.show)
        self.btn_run.clicked.connect(self.tabWidget.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SMS"))
        self.btn_run.setText(_translate("MainWindow", "Run"))
        self.lbl_sms.setText(_translate("MainWindow", "SMS"))
        self.btn_config.setText(_translate("MainWindow", "Config"))
        self.btn_zero.setText(_translate("MainWindow", "Zero"))
        self.lbl_supplier.setText(_translate("MainWindow", "Supplier:"))
        self.lbl_min.setText(_translate("MainWindow", "Min"))
        self.lbl_t.setText(_translate("MainWindow", "Type: "))
        self.lbl_max.setText(_translate("MainWindow", "Max"))
        self.btn_test.setText(_translate("MainWindow", "Test"))
        self.lbl_time.setText(_translate("MainWindow", "Time"))
        self.lbl_enabled.setText(_translate("MainWindow", "Enabled"))
        self.lbl_s.setText(_translate("MainWindow", "stax"))
        self.lbl_http.setText(_translate("MainWindow", "HTTP Link:"))
        self.lbl_type.setText(_translate("MainWindow", "http"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabstax), _translate("MainWindow", "stax"))
        self.lbl_s2.setText(_translate("MainWindow", "Supplier:"))
        self.lbl_min_2.setText(_translate("MainWindow", "Min"))
        self.lbl_time_2.setText(_translate("MainWindow", "Time"))
        self.lbl_t2.setText(_translate("MainWindow", "Type: "))
        self.lbl_type2.setText(_translate("MainWindow", "email"))
        self.lbl_max_2.setText(_translate("MainWindow", "Max"))
        self.lbl_supplier2.setText(_translate("MainWindow", "fps"))
        self.lbl_enabled2.setText(_translate("MainWindow", "Enabled"))
        self.btn_test_2.setText(_translate("MainWindow", "Test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabfps), _translate("MainWindow", "fps"))
        self.lbl_passwd_3.setText(_translate("MainWindow", "Password"))
        self.lbl_s3.setText(_translate("MainWindow", "Supplier:"))
        self.lbl_min_3.setText(_translate("MainWindow", "Min"))
        self.lbl_user_3.setText(_translate("MainWindow", "User"))
        self.lbl_mon.setText(_translate("MainWindow", "Monday"))
        self.lbl_t3.setText(_translate("MainWindow", "Type: "))
        self.btn_save.setText(_translate("MainWindow", "Test"))
        self.lbl_type3.setText(_translate("MainWindow", "Type: "))
        self.lbl_max_3.setText(_translate("MainWindow", "Max"))
        self.lbl_supplier_3.setText(_translate("MainWindow", "biztools"))
        self.lbl_enabled3.setText(_translate("MainWindow", "Enabled"))
        self.lbl_file_3.setText(_translate("MainWindow", "FTP Path"))
        self.lbl_fri.setText(_translate("MainWindow", "Friday"))
        self.lbl_thu.setText(_translate("MainWindow", "Thursday"))
        self.lbl_wed.setText(_translate("MainWindow", "Wednesday"))
        self.lbl_tue.setText(_translate("MainWindow", "Tuesday"))
        self.lbl_sun.setText(_translate("MainWindow", "Sunday"))
        self.lbl_sat.setText(_translate("MainWindow", "Saturday"))
        self.lbl_type3_2.setText(_translate("MainWindow", "Scheduled Run Times"))
        self.btn_add_time.setText(_translate("MainWindow", "+"))
        self.btn_remove_time2.setText(_translate("MainWindow", "-"))
        self.btn_remove_time1.setText(_translate("MainWindow", "-"))
        self.lbl_type3_3.setText(_translate("MainWindow", "Scheduled Run Days"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabbiztools), _translate("MainWindow", "biztools"))
        self.label_2.setText(_translate("MainWindow", "Amazon:"))
        self.label_3.setText(_translate("MainWindow", "Token:"))
        self.label_4.setText(_translate("MainWindow", "Token:"))
        self.label_5.setText(_translate("MainWindow", "Lead Shipping Time:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "tokens"))
        self.actiondygjdt.setText(_translate("MainWindow", "dygjdt"))


